### PR TITLE
package.json: update licenses tag to license

### PR DESCRIPTION
**Pull request by SatyaSudheer**
Fixes gh-101

### CODE REVIEW

**Comment by arthurvr** [comment]
LGTM. You can ignore the CI failure for now as it's on master too. Thanks!

**Comment by rxaviers** [comment]
Worth applying this change projects-wide, e.g... [Globlalize](https://github.com/jquery/globalize/blob/master/package.json#L89-L93), [UI](https://github.com/jquery/jquery-ui/blob/master/package.json) (cc @scottgonzalez @jzaefferer), [Mobile](https://github.com/jquery/jquery-mobile/blob/master/package.json#L16-L21) (@arschmitz), [PEP](https://github.com/jquery/PEP/blob/master/package.json#L15-L20) (cc @scottgonzalez), [Sizzle](https://github.com/jquery/sizzle/blob/master/package.json#L26-L30) (cc @gibson042). The other projects seems alright.

**Comment by arthurvr** [comment]
@kborchers Don't forget to include the [`Closes` thing](http://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines) when you merge PRs.

**Comment by arschmitz** [comment]
Too late...

**Comment by kborchers** [comment]
@arthurvr The commit message had Fixes gh-101 in it which closed the issue. Is that not good enough?

**Comment by scottgonzalez** [comment]
> The commit message had Fixes gh-101 in it which closed the issue. Is that not good enough?

No. Please see http://contribute.jquery.org/commits-and-pull-requests/#references.

**Pull request merged**
