### PR TITLE
RTL : Added CSSjanus to build process

### PR DESCRIPTION
**Pull request by thejdeep**
Added support for RTL using CSSjanus. Fixes Issue #37

### CODE REVIEW

**Comment by thejdeep** [comment]
@arschmitz Could you please review this sometime ?

**Comment by sfrisk** [comment]
Comments from meeting:

* Need to have RTL and regular CSS in one file so a site could support both options easily
* We should also go through existing scss files to figure out what needs to get flipped and what should be ignored.  In the case where we want things flipped, should we add a demo of these elements?

**Comment by rawteech** [comment]
So you will need have both the regular CSS file and the CSSjanus file as separate mixins but finally compiles to one CSS file I guess

**Comment by thejdeep** [comment]
@sfrisk @arschmitz Please review this sometime. Also, the Travis build fails because the Grunt task crosses 100 chars, can I break down the _build_ task

**Comment by sfrisk** [comment]
After discussing this in today's meeting, we've decided that CSSJanus might not be the best for this particular project, and we should probably be a bit more custom about how we handle RTL users, than generating RTL automatically.

**Pull request closed without merging**
