### PR TITLE
Fixes #81

### LINKED ISSUE #81: Typo on slim-underline() mixin
Hello,

There's a typo on your `slim-underline()` mixin.

The mixin says `@mixin slim-underline()` but the 'usage' example in the comment says `// Usage: @include slime-underline;`

_slim_ on one and _slime_ on the other.

https://github.com/jquery/css-chassis/blob/master/scss/atoms/typography/_mixins.scss

### PR DESCRIPTION
**Pull request by awayken**

### CODE REVIEW

**Comment by awayken** [comment]
I've submitted to the CLA as of a minute ago, but I'm not sure how long it takes for all that to propagate.

**Comment by arschmitz** [comment]
:+1: looks good to me

**Comment by sfrisk** [comment]
:+1:  Looks good

**Comment by sfrisk** [comment]
While this looks good, we decided to remove this functionality as of issue #84.  Thank you though for your help!

**Pull request closed without merging**
