### PR TITLE
Build: delete moot `.DS_Store` file

### PR DESCRIPTION
**Pull request by arthurvr**
This file doesn't add any value and can be safely deleted. It's a file OS X creates to store things like the folder background image or the position of the folder on your desktop.

@arschmitz This should be in your global gitignore file, fix your Git setup :p

### CODE REVIEW

**Comment by sfrisk** [comment]
Do you want to add it to `.gitignore` ? 

https://github.com/jquery/css-chassis/blob/master/.gitignore

**Comment by arthurvr** [comment]
> Do you want to add it to .gitignore ?
> 
> https://github.com/jquery/css-chassis/blob/master/.gitignore

If you prefer that, yes, happy to.

Though in fact it doesn't deserve in our gitignore, this is the reason global gitignore files exist. If you want to maintain them all here we could as well pull in this [whole list](https://github.com/github/gitignore/tree/master/Global)... WDYT @sfrisk?

**Comment by sfrisk** [comment]
Hrmm, point, and it doesn't seem like the other projects have this.  But it would be useful to make sure it is harder to accidentally include this file, or that we are just more diligent in checking PRs.

**Comment by arthurvr** [comment]
> But it would be useful to make sure it is harder to accidentally include this file, or that we are just more diligent in checking PRs.

Yes, and with for that exact same argument we can add add vim swap files, webstorm idea folders, Windows  thumbs files, ... and a huge bunch of other things. That's the reason global ignore files exist ;)

**Comment by cvrebert** [comment]
> Yes, and with for that exact same argument we can add add vim swap files, webstorm idea folders, Windows thumbs files, ... and a huge bunch of other things. That's the reason global ignore files exist ;)

Yes, but you're assuming that PR submitters are git-savvy, such that they know about global ignore files and took the time to set one up. IME, this is a bad assumption; I've seen numerous examples to the contrary.

**Comment by arthurvr** [comment]
On the meeting it was decided to land this, as it was discussed [earlier](https://github.com/jquery/css-chassis/pull/22#issuecomment-64685354) already.

> Yes, but you're assuming that PR submitters are git-savvy, such that they know about global ignore files and took the time to set one up. IME, this is a bad assumption;

IMHO this really fundamental part of a Git setup is pretty reasonable to expect from people. Just like we expect authors to setup their Git author data for the CLA.

**Comment by cvrebert** [comment]
Well, have fun asking folks to revise their PRs to remove random editor files in the future then. :wink: Hope it'll be a good use of y'all's time.

**Comment by geekman-rohit** [comment]
there are a lot of such files in windows and linux too. I don't really think we should add it to gitignore, I think just making sure such files don't get committed ought to be enough ?

**Comment by arthurvr** [comment]
> Well, have fun asking folks to revise their PRs to remove random editor files in the future then.  Hope it'll be a good use of y'all's time.

Well, if we don't add it to the gitignore that happens indeed. There's not really a way around that. If we'd add this one to gitignore, we will have just the same situation, but with other files.

**Comment by cvrebert** [comment]
> we will have just the same situation, but with other files.

True, but I've found that the Pareto principle is pretty applicable in this case.

**Comment by robbbz** [comment]
I agree with @geekman-rohit and @arthurvr. This is how Git was built for a reason, don't abuse the system.

> True, but I've found that the Pareto principle is pretty applicable in this case.

I haven't had that experience.

**Pull request closed without merging**
