### PR TITLE
Build: add accessibility testing

### LINKED ISSUE #99: Add Automated Accessibility Testing
Add automated testing to grunt that would take into account accessibility testing.

### PR DESCRIPTION
**Pull request by dylanb**
Fixes #99

### CODE REVIEW

**Comment by arschmitz** [comment]
@dylanb i assume this replaces #110 ?

**Comment by dylanb** [comment]
@arschmitz yes but I seem to have a conflict

**Comment by dylanb** [comment]
How do I find out what the merge conflicts are if I don't have write access to this repo?

**Comment by dylanb** [comment]
ok, my bad, did the wrong merge

**Pull request closed without merging**
