### PR TITLE
[WIP] typography: added color variables

### PR DESCRIPTION
**Pull request by xtina-starr**
fixes gh-119

coauthored with @theutahkate
This is a work in progress. We were curious if there was anything else within the _typography component that we could convert to use variables.

### CODE REVIEW

**Comment by sfrisk** [comment]
Just want to check to see how this is going, I know that @theutahkate was working on this Sunday of the jQuery Dev Summit.

**Comment by geekman-rohit** [comment]
also seems like @xtina-starr will need to sign the CLA http://contribute.jquery.org/CLA/

**Comment by xtina-starr** [comment]
I've signed it, but because I just have my first name on github it got
flagged as a suspicion name. Last I checked someone was suppose to manually
accept the CLA.

On Tuesday, October 27, 2015, Rohit Mulange <notifications@github.com>
wrote:

> also seems like @xtina-starr <https://github.com/xtina-starr> will need
> to sign the CLA http://contribute.jquery.org/CLA/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/css-chassis/pull/129#issuecomment-151609456>.
>


-- 
Christina Thompson
www.christinasthompson.com
305-801-6561

**Comment by sfrisk** [comment]
@xtina-starr I'll contact the people in charge of the CLA to deal with it.

**Comment by theutahkate** [comment]
Arg! Sorry. Yes, I have a bunch of work done on it, and have been slammed
since I got back, so haven't touched it. I was intending to open a pr to
replace Christina's, so we get around the CLA problem for now, too. So let
me do that, probably tonight.

**Comment by sfrisk** [comment]
Closing this in favor of the work continued in #134

**Pull request closed without merging**
