### PR TITLE
Fix "astrisk" [sic] typo

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by arschmitz** [comment]
@cvrebert Thanks for catching that! Think I could get you to sign our CLA?

**Comment by cvrebert** [comment]
Just signed it.

**Comment by arthurvr** [comment]
LGTM :+1: CLA looks good now.

**Comment by sfrisk** [comment]
Is this good to merge?

**Comment by arschmitz** [comment]
Yup i just have not got to any chassis stuff since yet to rebase and land it.

**Comment by sfrisk** [comment]
Okay, I can do it after the meeting today.

**Pull request closed without merging**
