### PR TITLE
Build: Must run variables task as part of the build

### PR DESCRIPTION
**Pull request by arschmitz**
This fixes the current CI failure

### CODE REVIEW

**Comment by jzaefferer** [comment]
Travis says NO

**Comment by sfrisk** [comment]
Looks like the `/dist` folder isn't getting created in time.

**Comment by geekman-rohit** [comment]
i pulled it in and ran Grunt, works fine :+1:

**Comment by geekman-rohit** [comment]
The folder needs to exist for jsass-vars to create the file. I just made the folder and ran things and everything went smoothly. 
should be more of a fix in jsass-vars to create any folders needed to create the file ?

**Comment by arschmitz** [comment]
@geekman-rohit your correct

**Comment by sfrisk** [comment]
If everyone is okay with this, I'm bringing it in.

**Comment by geekman-rohit** [comment]
LGTM :+1:

**Pull request closed without merging**
