### PR TITLE
Build: Upgrade JSCS

### PR DESCRIPTION
**Pull request by sfrisk**
Fixes gh-136

### CODE REVIEW

**Comment by geekman-rohit** [comment]
I don't think this update is going to solve our problem. grunt-jscs 2.3.0 is based on jscs 2.5.0
I checked and jscs 2.5.0 jquery preset does not include Indentation validation. Apparently the commit was reverted. (https://github.com/jscs-dev/node-jscs/commit/056770dd525397f947df1131982e0da9d41bcb73)

**Comment by arschmitz** [comment]
@geekman-rohit you can add the rule your self to our jscs.rc it was reverted because it is hard to enforce with so many possible edge cases

**Comment by geekman-rohit** [comment]
Yes, just commented because the reason we discussed updating jscs is not valid anymore. 
Updating is still a good idea though! 
:+1:

**Comment by sfrisk** [comment]
tested locally using the `"validateIndentation": "\t"` rule, but it is throwing a lot of errors. 

```
Running "jscs:all" (jscs) task
Expected indentation of 1 characters at Gruntfile.js :
     1 |module.exports = function( grunt ) {
     2 |var path = require( "path" );
---------^
     3 |require( "load-grunt-config" )( grunt, {
     4 | configPath: [
Expected indentation of 1 characters at Gruntfile.js :
     1 |module.exports = function( grunt ) {
     2 |var path = require( "path" );
     3 |require( "load-grunt-config" )( grunt, {
---------^
     4 | configPath: [
     5 |  path.join( process.cwd(), "tasks/options" ),
Expected indentation of 1 characters at scss/variables/breakpoints.js :
     9 |}( this, function( chassis ) {
    10 |
    11 |chassis.breakpoints = {
---------^
    12 |
    13 | "viewport-sm-min": {
Expected indentation of 2 characters at scss/variables/breakpoints.js :
    11 |chassis.breakpoints = {
    12 |
    13 | "viewport-sm-min": {
----------^
    14 |  name: "Viewport Breakpoint - Small Minimum Width",
    15 |  value: "400px"
Expected indentation of 2 characters at scss/variables/breakpoints.js :
    15 |  value: "400px"
    16 | },
    17 | "viewport-md-min": {
----------^
    18 |  name: "Viewport Breakpoint - Medium Minimum Width",
    19 |  value: "768px"
Expected indentation of 2 characters at scss/variables/breakpoints.js :
    19 |  value: "768px"
    20 | },
    21 | "viewport-lg-min": {
----------^
    22 |  name: "Viewport Breakpoint - Large Minimum Width",
    23 |  value: "920px"
Expected indentation of 2 characters at scss/variables/breakpoints.js :
    23 |  value: "920px"
    24 | },
    25 | "viewport-xl-min": {
----------^
    26 |  name: "Viewport - Extra Large Minimum Width",
    27 |  value: "1200px"
Expected indentation of 1 characters at scss/variables/breakpoints.js :
    27 |  value: "1200px"
    28 | }
    29 |};
---------^
    30 |
    31 |return chassis;
Expected indentation of 1 characters at scss/variables/breakpoints.js :
    29 |};
    30 |
    31 |return chassis;
---------^
    32 |} ) );
    33 |
Expected indentation of 1 characters at scss/variables/chassis.js :
    10 | }
    11 |}( this, function() {
    12 |return {};
---------^
    13 |} ) );
    14 |
Expected indentation of 1 characters at scss/variables/colors.js :
     9 |}( this, function( chassis ) {
    10 |
    11 |var colors = {
---------^
    12 | "chassis-gray-dark": {
    13 |  "value": "#383838",
Expected indentation of 1 characters at scss/variables/colors.js :
    35 | }
    36 |};
    37 |chassis.colors = {
---------^
    38 | "background": colors[ "chassis-gray-dark" ],
    39 | "font": colors[ "chassis-gray-dark" ],
Expected indentation of 1 characters at scss/variables/colors.js :
    46 | }
    47 |};
    48 |return chassis;
---------^
    49 |} ) );
    50 |
Expected indentation of 1 characters at scss/variables/template.js :
    11 |}( this, function() {
    12 |
    13 |//>> return chasses.moduleName;
---------^
    14 |} ) );
    15 |
Expected indentation of 1 characters at scss/variables/typography.js :
     9 |}( this, function( chassis ) {
    10 |
    11 |var color = "#222",
---------^
    12 | fontSize = "20px",
    13 | lineHeight = 1.5;
Expected indentation of 1 characters at scss/variables/typography.js :
    13 | lineHeight = 1.5;
    14 |
    15 |chassis.typography = {
---------^
    16 | normal: {
    17 |  name: "Font weight - Normal",
Expected indentation of 1 characters at scss/variables/typography.js :
    56 |};
    57 |
    58 |return chassis;
---------^
    59 |} ) );
    60 |
Expected indentation of 1 characters at tasks/alias.js :
     1 |module.exports = function( grunt ) {
     2 |grunt.registerTask( "default", [ "test" ] );
---------^
     3 |grunt.registerTask( "test", [ "build", "jshint", "jscs", "csslint", "htmllint" ] );
     4 |grunt.registerTask( "build", [ "variables", "svg", "sass", "csscomb", "cssmin" ] );
Expected indentation of 1 characters at tasks/alias.js :
     1 |module.exports = function( grunt ) {
     2 |grunt.registerTask( "default", [ "test" ] );
     3 |grunt.registerTask( "test", [ "build", "jshint", "jscs", "csslint", "htmllint" ] );
---------^
     4 |grunt.registerTask( "build", [ "variables", "svg", "sass", "csscomb", "cssmin" ] );
     5 |grunt.registerTask( "perf", [
Expected indentation of 1 characters at tasks/alias.js :
     2 |grunt.registerTask( "default", [ "test" ] );
     3 |grunt.registerTask( "test", [ "build", "jshint", "jscs", "csslint", "htmllint" ] );
     4 |grunt.registerTask( "build", [ "variables", "svg", "sass", "csscomb", "cssmin" ] );
---------^
     5 |grunt.registerTask( "perf", [
     6 | "start-selenium-server",
Expected indentation of 1 characters at tasks/alias.js :
     3 |grunt.registerTask( "test", [ "build", "jshint", "jscs", "csslint", "htmllint" ] );
     4 |grunt.registerTask( "build", [ "variables", "svg", "sass", "csscomb", "cssmin" ] );
     5 |grunt.registerTask( "perf", [
---------^
     6 | "start-selenium-server",
     7 | "connect:perf",
Expected indentation of 1 characters at tasks/alias.js :
     9 | "stop-selenium-server"
    10 |] );
    11 |grunt.registerTask( "svg", [ "svgmin", "svgstore" ] );
---------^
    12 |};
    13 |
Expected indentation of 1 characters at tasks/options/perfjankie.js :
     1 |module.exports = function( grunt ) {
     2 |grunt.loadNpmTasks( "perfjankie" );
---------^
     3 |
     4 |return {
Expected indentation of 1 characters at tasks/options/perfjankie.js :
     2 |grunt.loadNpmTasks( "perfjankie" );
     3 |
     4 |return {
---------^
     5 | options: {
     6 |  suite: "perfSlides - Performance Analysis"
```

**Pull request merged**
