### PR TITLE
Performance: Add BEM-Components to test suite

### PR DESCRIPTION
**Pull request by geekman-rohit**
This Pull Request adds [bem-components](https://github.com/bem/bem-components) framework to the performance test suite. It also adds a custom built css file form bem-components in external directory.

### CODE REVIEW

**Comment by arschmitz** [comment]
Im holding off on this until i land some changes to where we are getting the build files from. Going to move to local copies on everything to remove network overhead.

**Comment by robbbz** [comment]
@arschmitz Is this done now?

**Comment by arschmitz** [comment]
@robbbz sadly no other work has been blocking me getting to this i do hope to loop back to the perf testing soon though :-(

**Comment by sfrisk** [comment]
Based on the discussion at today's meeting, this is old and has been blocked for a long time, so I'm closing this in favor of working on the SCSS side of the application.

**Pull request closed without merging**
